// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package accelerate_to_zero

type AccreditationOrg struct {
	ID           string         `json:"id"`
	Name         string         `json:"name"`
	Certificates []*Certificate `json:"certificates"`
	Website      string         `json:"website"`
}

type Certificate struct {
	ID           string            `json:"id"`
	Name         string            `json:"name"`
	AccreditedBy *AccreditationOrg `json:"accreditedBy"`
}

type Company struct {
	ID            string         `json:"id"`
	Accreditation []*Certificate `json:"accreditation"`
}
