
service: accelerate-to-zero-scraper

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs8.10
  stage: "${env:ENVIRONMENT}"
  region: "${env:REGION}"
  environment:
    ENVIRONMENT: ${self:provider.stage}
    REGION: ${self:provider.region}
  iamRoleStatements:

functions:
  scrape:
    name: "${self:service}-${self:provider.stage}"
    handler: index.handler
    events:
      - schedule: rate(200 minutes)
